[package]
edition = "2021"
name = "express-risc0-adapter"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
borsh = { workspace = true }
express-zkvm = { workspace = true }
# risc0-zkvm = { version = "1.0.3", features = ["prove"] }
risc0-zkvm = { version = "1.0.3", features = ["prove"] }
serde = { workspace = true }
serde_json = { workspace = true }

[features]
default = []
# prover = ["dep:risc0-zkvm"]
prover = []
