[package]
edition = "2021"
name = "express-reth-evm"
version = "0.1.0"

[dependencies]
express-reth-primitives = { workspace = true }
reth-chainspec = { workspace = true }
reth-evm = { workspace = true }
reth-evm-ethereum = { workspace = true }
reth-node-ethereum = { workspace = true }
reth-primitives = { workspace = true }
revm = { workspace = true }
revm-primitives = { workspace = true }
