[package]
name = "alpen-vertex-state"
version = "0.1.0"
edition = "2021"

# Note: Since we want to keep the core consensus logic generic, we shouldn't
# reuse much of reth in this crate so that we can factor it all out eventually.

[dependencies]
alpen-vertex-primitives = { workspace = true }
