[package]
name = "alpen-nero-sequencer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "alpen-nero-sequencer"
path = "src/main.rs"

[dependencies]
alpen-nero-common = { workspace = true }
alpen-nero-primitives = { workspace = true }
alpen-nero-rpc-api = { workspace = true }

reth-ipc = { workspace = true }
reth-rpc-api = { workspace = true } 
tracing = { workspace = true }
