[package]
name = "alpen-vertex-sequencer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "alpen-vertex-sequencer"
path = "src/main.rs"

[dependencies]
alpen-vertex-common = { workspace = true }
alpen-vertex-primitives = { workspace = true }
alpen-vertex-rpc-api = { workspace = true }

async-trait = { workspace = true }
jsonrpsee = { workspace = true, features = ["server", "macros"] }
reth-ipc = { workspace = true }
reth-primitives = { workspace = true }
reth-rpc-api = { workspace = true }
reth-rpc-types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
