[package]
name = "alpen-vertex-sequencer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "alpen-vertex-sequencer"
path = "src/main.rs"

[dependencies]
alpen-vertex-common = { workspace = true }
alpen-vertex-primitives = { workspace = true }
alpen-vertex-rpc-api = { workspace = true }

reth-ipc = { workspace = true }
reth-rpc-api = { workspace = true } 
tracing = { workspace = true }
