[workspace]
members = [
        "crates/common",
        "sequencer",
]

default-members = [
        "sequencer",
]

resolver = "2"

[workspace.dependencies]
alpen-nero-common = { path = "crates/common" }

tracing = "0.1"
tracing-subscriber = "0.3"
