[workspace]
members = [
	"crates/btcio",
        "crates/common",
        "crates/consensus-logic",
	"crates/db",
	"crates/evmctl",
	"crates/evmexec",
        "crates/primitives",
        "crates/rpc/api",
        "crates/state",
	"crates/util/mmr",
	"crates/vtxjmt",
        "sequencer",
]

default-members = [
        "sequencer",
]

resolver = "2"

[workspace.dependencies]
alpen-vertex-common = { path = "crates/common" }
alpen-vertex-db = { path = "crates/db" }
alpen-vertex-mmr = { path = "crates/util/mmr" }
alpen-vertex-primitives = { path = "crates/primitives" }
alpen-vertex-rpc-api = { path = "crates/rpc/api" }
alpen-vertex-state = { path = "crates/state" }

anyhow = "1.0.86"
arbitrary = { version = "1.3.2", features = ["derive"] }
async-trait = "0.1"
borsh = { version = "1.5.0", features = ["derive"] }
jsonrpsee = "0.22"
jsonrpsee-core = "0.22"
jsonrpsee-types = "0.22"
reth-db = { git = "https://github.com/paradigmxyz/reth.git", tag = "v0.2.0-beta.6" }
reth-ipc = { git = "https://github.com/paradigmxyz/reth.git", tag = "v0.2.0-beta.6" }
reth-primitives = { git = "https://github.com/paradigmxyz/reth.git", tag = "v0.2.0-beta.6" }
reth-revm = { git = "https://github.com/paradigmxyz/reth.git", tag = "v0.2.0-beta.6" }
reth-rpc-api = { git = "https://github.com/paradigmxyz/reth.git", tag = "v0.2.0-beta.6" }
reth-rpc-types = { git = "https://github.com/paradigmxyz/reth.git", tag = "v0.2.0-beta.6" }
rockbound = { git = "https://github.com/sovereign-Labs/rockbound", tag = "v2.0.1" }
rocksdb = "0.21"
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.37", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"