[l1_config]
rpc_url = "http://localhost:18332"
rpc_user = "alpen"
rpc_password = "alpen"
network = "regtest"

[rollup_config]
l1_start_block_height = 4
l1_follow_distance = 6
rpc_port = 8432
block_time = 250
datadir = "/path/to/data/directory"

# optional
# sequencer_key = "/path/to/data/directory/" 

[reader_config]
max_reorg_depth = 4
client_poll_dur_ms = 200
