[reader_config]
max_reorg_depth = 4
client_poll_dur_ms = 200

[bitcoind_rpc]
rpc_url = "http://localhost:18332"
rpc_user = "alpen"
rpc_password = "alpen"
network = "regtest"

[client]
rpc_port = 8432
datadir = "/path/to/data/directory"
# sequencer_key = "/path/to/data/directory/" 

[sync]
l1_follow_distance = 6
max_reorg_depth = 4
client_poll_dur_ms = 200
