[package]
name = "risc0-guest-builder"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]
risc0-build = { version = "1.0.5" }

[package.metadata.risc0]
methods = ["guest-reth-stf"]

[features]
default = []
prover = []
