[package]
edition = "2021"
name = "cl-block-stf"
version = "0.1.0"

[workspace]

[dependencies]
alpen-express-primitives = { path = "../../../crates/primitives" }
borsh = { version = "1.5.0", features = ["derive"] }
express-cl-stf = { path = "../../../crates/prover/cl-stf" }
risc0-zkvm = { version = "1.0.5", default-features = false, features = ['std'] }
