[package]
name = "express-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
alpen-express-db = { workspace = true }
alpen-express-state = { workspace = true }

threadpool = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }