[package]
name = "express-chaintsn"
version = "0.1.0"
edition = "2021"

[dependencies]
alpen-express-primitives = { workspace = true }
alpen-express-state = { workspace = true }

thiserror = { workspace = true }
tracing = { workspace = true, optional = true }

[features]
default = ["std"]
std = ["dep:tracing"]
