[package]
edition = "2021"
name = "reth-sp1"
version = "0.1.0"

[workspace]

[dependencies]
revm = { version = "12.1.0", default-features = false }
sp1-zkvm = "1.0.1"
zkvm-primitives = { path = "../../../crates/prover/primitives" }
