[package]
name = "alpen-vertex-primitives"
version = "0.1.0"
edition = "2021"

[dependencies]
arbitrary = { workspace = true }
borsh = { workspace = true }
hex = { workspace = true }
reth-primitives = { workspace = true }
