[package]
edition = "2021"
name = "guest-sp1-evm-ee-stf"
version = "0.1.0"

[workspace]

[dependencies]
express-proofimpl-evm-ee-stf = { path = "../../../crates/proof-impl/evm-ee-stf" }
revm = { version = "12.1.0", default-features = false }
sp1-zkvm = { version = "2.0.0" }

[patch.crates-io]
secp256k1 = { git = "https://github.com/prajwolrg/rust-secp256k1", branch = "0.29.x-sp1-patch" }
