[package]
edition = "2021"
name = "bitcoin-blockspace"
version = "0.1.0"

[dependencies]
bitcoin = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
sha2.workspace = true

[dev-dependencies]
alpen-test-utils.workspace = true
hex.workspace = true
