[package]
name = "l1-batch"
version = "0.1.0"
edition = "2021"

[dependencies]
alpen-express-primitives.workspace = true
anyhow.workspace = true
bitcoin.workspace = true
borsh.workspace = true
btc-blockspace.workspace = true
ethnum = "1.5.0"
serde.workspace = true
serde_json = "1.0.127"

[dev-dependencies]
alpen-test-utils.workspace = true
rand.workspace = true
