[package]
name = "alpen-vertex-evmexec"
version = "0.1.0"
edition = "2021"

[dependencies]
alpen-vertex-evmctl = { workspace = true }
alpen-vertex-primitives = { workspace = true }
alpen-vertex-state = { workspace = true }
arbitrary = { workspace = true }
borsh = { workspace = true }
reth-primitives = { workspace = true }
reth-node-ethereum = { workspace = true }
reth-rpc = { workspace = true }
reth-rpc-api = { workspace = true }
reth-rpc-types = { workspace = true }
jsonrpsee = { workspace = true }
tokio = { workspace = true }
http = "0.2.8"
hyper = "0.14.25"
tower = "0.4"
serde = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
