[package]
name = "alpen-vertex-btcio"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
bitcoin = { workspace = true }
bytes =  { version = "1.6.0" }
tokio = { workspace = true }
tracing = { workspace = true }
zeromq = { version = "0.3.5" }
