[package]
edition = "2021"
name = "guest-btc-blockspace-sp1"
version = "0.1.0"

[workspace]

[dependencies]
bincode = "1.3.3"
bitcoin = { version = "0.32.1" }
btc-blockspace = { path = "../../../crates/prover/btc-blockspace" }
l1-batch = { path = "../../../crates/prover/l1-batch" }
sha2 = "0.10.8"
sp1-zkvm = { version = "1.0.1", features = ["verify"] }


[patch.crates-io]
sha2-v0-9-8 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", branch = "patch-sha2-v0.9.8" }
sha2-v0-10-6 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", branch = "patch-sha2-v0.10.6" }
sha2-v0-10-8 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", branch = "patch-sha2-v0.10.8" }
