[package]
name = "risc0-adapter"
version = "0.1.0"
edition = "2021"

[dependencies]
zkvm = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }
risc0-zkvm = { version = "1.0.2" }