[package]
name = "reth-risc0"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
revm = { version = "12.1.0", default-features = false }
risc0-zkvm = { version = "1.0.5", default-features = false, features = ['std'] }
zkvm-primitives = { path = "../../../crates/prover/primitives" }
